[#ERROR_PLACEHOLDER] Error: the name: `foo` is defined multiple times
   ╭─[redef:1:1]
   │
 1 │ fn foo() {}
 2 │ fn foo() {}
   │ ────┬───  
   │     ╰───── `foo` redefined here
───╯
[#ERROR_PLACEHOLDER] Error: the name: `foo` is defined multiple times
   ╭─[redef:1:1]
   │
 1 │ fn foo() {}
   │ 
 3 │ fn foo() {}
   │ ────┬───  
   │     ╰───── `foo` redefined here
───╯
[#ERROR_PLACEHOLDER] Error: `main` function not found in ...
   ╭─[redef:1:1]
   │
 1 │ fn foo() {}
───╯
